<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\FrameIt.ico</ApplicationIcon>
    <Platforms>x64</Platforms>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AssemblyName>FrameIt</AssemblyName>
    <RootNamespace>FrameIt</RootNamespace>
    <NoWarn>$(NoWarn);WFAC010</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\FrameIt.ico" />
    <Resource Include="Assets\FrameIt-256.png" />
  </ItemGroup>
</Project>
